server:
  port: 8800
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl: none
  h2:
    console.enabled: true