
CREATE TABLE UNDERLIER_CATEGORY (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UNDERLIER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(10) NOT NULL,
    CATEGORY_ID INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT FK_UNDERLIER_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES UNDERLIER_CATEGORY(ID)
);