
CREATE TABLE UNDERLIER_CATEGORY (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UNDERLIER (
    id INTEGER NOT NULL AUTO_INCREMENT,
    code VARCHAR(10) NOT NULL,
    category_id INTEGER,
    PRIMARY KEY (id),
    CONSTRAINT FK_UNDERLIER_CATEGORY FOREIGN KEY (category_id) REFERENCES UNDERLIER_CATEGORY(id)
);